#Importação das bibliotecas

In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Criar a base de dados

In [50]:
data = {
    'comentario': [
        # Comentários positivos (2)
        'A bolsa é maravilhosa, feita com muito carinho!',
        'Perfeita! Trabalho impecável, super indico.',
        'Linda demais, me apaixonei pela bolsa.',
        'Qualidade excelente, chegou antes do prazo!',
        'Muito capricho e cuidado em cada detalhe.',
        'Fiquei encantada, recomendo demais.',
        'Ótimo atendimento e produto incrível.',
        'A bolsa é linda, feita com amor. Parabéns!',
        'Super satisfeita! Comprarei novamente.',
        'Excelente qualidade, fiquei impressionada!',
        'Trabalho lindo, super delicado, amei.',
        'Bolsas maravilhosas, entrega rápida.',
        'Apaixonada pelo trabalho dessa loja!',
        'Perfeição define, muito feliz com a compra.',
        'Tudo impecável, desde o atendimento até o produto.',
        'Que trabalho lindo, superou minhas expectativas.',
        'Perfeita! Muito melhor do que na foto.',
        'Atendimento nota 10 e qualidade surreal.',
        'Simplesmente perfeita, amei demais.',
        'Produto incrível, super recomendo.',
        'Trabalho feito com muito amor, parabéns!',
        'Fiquei apaixonada, muito capricho.',
        'Excelente! Voltarei a comprar com certeza.',
        'Tudo perfeito, muito satisfeita.',
        'Bolsas lindas e muito bem feitas.',
        'Perfeito do começo ao fim.',
        'Maravilhosa! Produto de altíssima qualidade.',
        'Surpreendente, superou minhas expectativas.',
        'Amei cada detalhe, perfeito!',
        'Maravilhoso! Produto e atendimento incríveis.',
        'Sem palavras, ficou perfeito.',
        'Muito bem embalado, chegou impecável.',
        'Trabalho impecável, lindo demais.',
        'Perfeição em cada ponto, parabéns.',
        'Fiquei encantada com tanto capricho.',
        'Atendimento excelente, produto perfeito.',
        'Chegou super rápido e muito bem feito.',
        'Amei, muito mais bonita que na foto.',
        'Produto perfeito, muito satisfeita.',
        'Encantada com a qualidade!',
        'Ficou maravilhosa, recomendo muito.',
        'Perfeição, atendimento maravilhoso.',
        'Ótima qualidade, muito capricho.',
        'Tudo feito com muito amor e cuidado.',
        'Fiquei muito satisfeita, parabéns!',
        'Amei! Comprarei outras cores.',
        'Muito mais bonita pessoalmente.',
        'Trabalho maravilhoso, super recomendo.',
        'Encantada, é muito linda.',
        'Atendimento rápido, entrega perfeita.',
        'Fiquei surpresa com tanta qualidade.',
        'Produto de excelência, parabéns!',
        'É perfeita, amei cada detalhe.',
        'Ficou linda, ótima qualidade.',
        'Amei demais, comprarei de novo.',
        'Perfeito, do jeitinho que pedi.',
        'Muito caprichosa, trabalho impecável.',
        'Bolsas maravilhosas, atendimento top.',
        'Qualidade absurda, parabéns!',
        'Trabalho espetacular, nota 10.',
        'Maravilhosa, linda demais.',
        'Produto de primeira, recomendo.',
        'Ficou perfeita, exatamente como pedi.',
        'Apaixonada! Muito bem feito.',
        'Atendimento excepcional, muito satisfeita.',
        'Tudo perfeito, super recomendo.',
        'A bolsa é um encanto, maravilhosa.',
        'Perfeição total, amei tudo.',
        'Produto lindo e de qualidade.',
        'Adorei! Ficou muito bonita.',
        'Entrega rápida e qualidade incrível.',
        'Bolsas lindas, muito satisfeita.',
        'Trabalho maravilhoso, parabéns.',
        'Tudo impecável, nota mil.',
        'Amei! Superou minhas expectativas.',
        'Simplesmente linda, muito capricho.',
        'Perfeita em todos os detalhes.',
        'Fiquei encantada, amei muito.',
        'Atendimento maravilhoso e entrega rápida.',
        'Produto impecável, super recomendo.',
        'Ficou maravilhosa, muito feliz.',
        'Trabalho impecável, de muita qualidade.',
        'Encantada, muito melhor do que imaginei.',
        'Chegou rápido e muito bem feito.',
        'Perfeita, do jeitinho que eu queria.',
        'Muito bem feita, amei.',
        'Tudo perfeito, parabéns pelo trabalho.',
        'Entrega rápida, qualidade sensacional.',
        'Apaixonada pela minha bolsa!',
        'Trabalho lindo, parabéns.',
        'Amei, muito satisfeita.',
        'Tudo impecável, recomendo demais.',
        'Produto incrível, qualidade excelente.',
        'Amei! Atendimento top e produto perfeito.',
        'Perfeição do começo ao fim.',
        'Muito caprichosa, parabéns!',
        'Qualidade excelente, recomendo muito.',
        'Maravilhoso, simplesmente incrível.',
        'Lindo demais, super satisfeita.',
        'Encantada com tanto capricho.',
        'Ótima qualidade, muito satisfeita.',

        # Comentários neutros (1)
        'Produto conforme anunciado.',
        'Chegou no prazo, tudo certo.',
        'Atendimento ok, sem problemas.',
        'Tudo certo com a entrega.',
        'Recebi dentro do prazo.',
        'Corresponde ao que foi mostrado.',
        'Nada a reclamar, tudo certo.',
        'A bolsa é como na foto.',
        'Entrega normal, produto ok.',
        'Sem surpresas, conforme descrição.',
        'O produto é bom, mas nada além.',
        'Achei normal, dentro do esperado.',
        'Cor um pouco diferente, mas ok.',
        'Tamanho ok, não surpreendeu.',
        'Tudo certo, entrega ok.',
        'Bolsa simples, porém funcional.',
        'Produto correto, chegou como combinado.',
        'Chegou no tempo certo.',
        'Recebi direitinho, tudo em ordem.',
        'Dentro do que foi prometido.',
        'Não é nada de outro mundo, mas ok.',
        'Entrega conforme combinado.',
        'Sem grandes problemas, tudo certo.',
        'Básica, mas cumpre o prometido.',
        'Atendimento correto, sem problemas.',
        'Produto honesto, nada a destacar.',
        'A embalagem poderia ser melhor.',
        'Produto simples, mas funciona.',
        'Recebi normalmente, produto ok.',
        'Entrega no prazo, produto correto.',
        'Tudo como anunciado.',
        'Nenhuma surpresa, nem boa nem ruim.',
        'Padrão, dentro do esperado.',
        'Produto condiz com o site.',
        'Tudo certo até aqui.',
        'Cor diferente, mas o produto é bom.',
        'Recebi no tempo, produto bom.',
        'Tudo dentro do combinado.',
        'Atendimento padrão, ok.',
        'O produto é simples, mas cumpre.',
        'Nenhum problema na entrega.',
        'O trabalho é bom, mas não impressiona.',
        'Recebi sem nenhum problema.',
        'A entrega foi feita corretamente.',
        'Produto dentro do esperado.',
        'Tudo certo, produto chegou bem.',
        'A descrição foi fiel.',
        'Nada que surpreenda, mas ok.',
        'Recebi como esperado.',
        'Tudo certo, mas sem diferencial.',
        'Produto básico, mas bom.',
        'Correta a entrega.',
        'Produto funcional, sem erros.',
        'Nenhuma surpresa.',
        'Produto ok, chegou certo.',
        'Produto simples e correto.',
        'Cumpriu o que prometeu.',
        'Tudo conforme anunciado.',
        'Chegou como descrito.',
        'Entrega no prazo, tudo certo.',
        'Nada além do esperado.',
        'Produto ok, sem defeitos.',
        'Entrega rápida, produto comum.',
        'Básico, mas funcional.',
        'Recebi no prazo, sem surpresas.',
        'Produto como no anúncio.',
        'Produto correto e funcional.',
        'Recebi normalmente.',
        'Dentro do combinado.',
        'Nada de mais, mas ok.',
        'Tudo nos conformes.',
        'Entrega no tempo certo.',
        'Produto razoável.',
        'Corresponde ao que foi prometido.',
        'Chegou no prazo, produto simples.',
        'Produto bem embalado, ok.',
        'Tudo certo, produto honesto.',
        'Cor ok, mas não é perfeita.',
        'Recebi certinho.',
        'Entrega ok, produto ok.',
        'Tudo certo, entrega e produto.',
        'Produto correto, entrega correta.',
        'Ok, mas esperava mais.',
        'Produto como anunciado, tudo certo.',
        'Nada demais, produto ok.',
        'Atendimento normal.',
        'Sem novidades, produto ok.',
        'Entrega e produto no padrão.',
        'Dentro do esperado, normal.',
        'Tudo certo, nada a destacar.',
        'Produto chegou bem.',
        'Simples, mas é isso mesmo.',
        'Produto sem defeitos.',
        'Entrega certinha.',
        'Recebi dentro do prazo, sem problemas.',
        'Cor não igual, mas boa.',
        'Produto e entrega corretos.',
        'Produto e atendimento normais.',

        # Comentários negativos (0)
        'Péssima qualidade, muito ruim.',
        'Veio toda torta, horrível.',
        'Muito mal feito, que lixo.',
        'Bolsa ridícula, péssima.',
        'Rasgou no primeiro uso.',
        'Cheiro forte, insuportável.',
        'Parece feita nas coxas.',
        'Dinheiro jogado fora.',
        'Produto de quinta, lixo.',
        'Entrega péssima, muito atraso.',
        'Desrespeito total, não respondem.',
        'Me senti enganada.',
        'Horrível, não recomendo.',
        'Produto muito ruim.',
        'Parece brinquedo de criança.',
        'Trabalho mal feito.',
        'Falta de respeito com o cliente.',
        'Veio todo errado.',
        'Atendimento lixo.',
        'Uma bela porcaria.',
        'Se arrependimento matasse...',
        'Rasgou todo.',
        'Não vale o preço.',
        'Uma vergonha isso.',
        'Parece feito de papelão.',
        'Desastre total.',
        'O zíper quebrou no primeiro dia.',
        'Parece coisa de camelô.',
        'Péssima experiência.',
        'Demorou muito e veio errado.',
        'Pior compra da vida.',
        'Produto veio sujo.',
        'Fio solto pra todo lado.',
        'Horrível, sério.',
        'A vendedora sumiu.',
        'Material podre.',
        'Chegou todo amassado.',
        'Produto todo defeituoso.',
        'Decepcionante.',
        'Uma piada isso.',
        'Que lixo.',
        'Nunca mais compro aqui.',
        'Produto todo torto.',
        'Serviço porco.',
        'Acabamento horrível.',
        'Muito frágil, péssimo.',
        'Decepção total.',
        'Falta de capricho.',
        'Parece resto de material.',
        'Atendimento péssimo.',
        'Produto uma bosta.',
        'Chegou fedendo.',
        'Fiquei p*** da vida.',
        'Veio quebrado.',
        'Parece feito com os pés.',
        'Bolsa podre.',
        'Material horroroso.',
        'Uma enganação.',
        'Roubo, sério.',
        'Parece bolsa de feira.',
        'Perdi meu dinheiro.',
        'Misericórdia, que horror.',
        'Tá de sacanagem.',
        'Bolsa horrível.',
        'Parece coisa de sucata.',
        'Pior que imaginava.',
        'Material vagabundo.',
        'Odiei, sério.',
        'Isso é um golpe.',
        'Fiquei revoltada.',
        'Cheirando mofo.',
        'Tecido horroroso.',
        'Sem acabamento nenhum.',
        'Produto horrível.',
        'Nunca vi coisa tão mal feita.',
        'Entrega péssima.',
        'Me sinto roubada.',
        'Sem condições, que lixo.',
        'Produto horroroso.',
        'Trabalho terrível.',
        'Bolsa desmontou toda.',
        'Fios soltos em tudo.',
        'Me senti lesada.',
        'Atendimento zero.',
        'Horrível em todos os sentidos.',
        'Deus me livre.',
        'Lixo total.',
        'Não dá pra usar.',
        'Cuidado, é cilada.',
        'Produto horrível, não recomendo.',
        'Parece feito de saco velho.',
        'Veio com manchas horríveis.',
        'Tecido de péssima qualidade.',
        'Decepcionante em tudo.',
        'Entrega atrasou horrores.',
        'Muito mal costurada.',
        'Bolsa parece brinquedo quebrado.',
        'A pior compra que já fiz.',
        'Fiquei extremamente decepcionada.',
        'É um lixo, pura enganação.',
        'Uma bosta'
    ],
    'label': [
        2]*100 + [1]*100 + [0]*100
}
#Verificar quantidade de cada label
df = pd.DataFrame(data)


#Vetoriação dos textos

In [51]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['comentario'])
y = df['label']

#Divisão dos dados

In [52]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Treinamento

In [53]:
Modelo_naive_bayes = MultinomialNB()
Modelo_naive_bayes.fit(x_train, y_train)

MultinomialNB()

#Avaliação

In [54]:
#Predição
y_pred = Modelo_naive_bayes.predict(x_test)
#Avaliação
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print("Acurácia:", accuracy)
print("Matriz de Confusão:")
print(confusion)
print("Relatório de Classificação:")
print(classification_rep)

Acurácia: 0.9166666666666666
Matriz de Confusão:
[[19  2  1]
 [ 1 15  0]
 [ 1  0 21]]
Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.90      0.86      0.88        22
           1       0.88      0.94      0.91        16
           2       0.95      0.95      0.95        22

    accuracy                           0.92        60
   macro avg       0.91      0.92      0.92        60
weighted avg       0.92      0.92      0.92        60



Testes

In [55]:
while True:
    novo_comentario = input("\nDigite o texto do comentário para classificar (ou 'sair' para encerrar):\n")
    if novo_comentario.lower() == 'sair':
        break
    novo_comentario_vect = vectorizer.transform([novo_comentario])
    pred = Modelo_naive_bayes.predict(novo_comentario_vect)

    if pred[0] == 2:
        print("🟢 Este comentário é classificado como: POSITIVO\n")
    elif pred[0] == 1:
        print("Este comentário é classificado como: NEUTRO\n")
    else:
        print("🔴 Este e-mail é classificado como: NEGATIVO\n")


Digite o texto do comentário para classificar (ou 'sair' para encerrar):
Muito ruim a bolsa. Não compraria novamente
🔴 Este e-mail é classificado como: NEGATIVO


Digite o texto do comentário para classificar (ou 'sair' para encerrar):
Fodaaa, muito top
🟢 Este comentário é classificado como: POSITIVO


Digite o texto do comentário para classificar (ou 'sair' para encerrar):
Bolsa Ok
🟢 Este comentário é classificado como: NEUTRO


Digite o texto do comentário para classificar (ou 'sair' para encerrar):
sair
